version: '4.3.0-{build}'
image: Visual Studio 2015
configuration: Release
platform: Any CPU
before_build:
- cmd: nuget.exe restore ReasonCodeExample.XPathTools.sln
build:
  verbosity: minimal
test:
  categories:
    except:
    - Integration
artifacts:
- path: ReasonCodeExample.XPathTools/bin/release/*.vsix
  name: VSIX